version:  0.2

phases:
  install:
    commands:
      # Install Node latest
      - echo "Installing Nodejs LTR"
      - curl -sL https://deb.nodesource.com/setup_12.x | bash -
      - apt install -y nodejs
      # Install AWSCLI latest
      - echo "Check Python version"
      - python -V
      - echo "Check PIP Version"
      - pip -V
      - echo "Install and Upgrade AWSCLI"
      - pip install --upgrade pip
      - pip install --upgrade awscli
      - echo "Check AWSCLI version"
      - aws --version
      # - echo Installing npm vue-cli, express and serverless
      # - npm install -g @vue/cli
      - npm install -g serverless
      - npm install -g serverless-offline
      - echo "Copy Variables.ENV from s3bucket"
      - aws s3 cp s3://cloudinaja-cicd/wed/api/variables.env .
      - ls | grep variables.env
      # RUN npm run build
  # pre-build:
  #   commands:
  #     # install depedencies
  #     # - npm install .
  build:
    commands:
      # Test
      # - echo Testing...
      # - echo "PATH"
      # - pwd
      # - ls
      # # build
      - echo "serverless deploy"...
      - serverless deploy
      # - npm run build
# artifacts:
#   files:
#     - "**/*"
#   discard-paths: no
#   base-directory: dist
